[tool.poetry]
name = "bookmarks"
version = "0.1.0"
description = "Demo Social Media Website Project"
authors = ["David J Nevin <content@davidjnevin.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Django = "~=4.1.0"
Pillow = "^9.2.0"
python-decouple = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
